Register macro expansion capabilities
software-mansion/scarb pull request #1195
Opened 2024-03-15 19:03 UTC by maciektr

**Stack**:
- #1195 ⬅
- #1194
- #1192
- #1186
- #1188

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-03-18 15:17 UTC, mkaput requested changes

2024-03-18 15:17 UTC, mkaput commented on plugins/cairo-lang-macro/src/lib.rs
> +pub static MACRO_DEFINITIONS_SLICE: [ExpansionDefinition];
shouldn't this be doc(hidden)?

2024-03-18 15:17 UTC, mkaput commented on plugins/cairo-lang-macro/src/lib.rs
> +}
doc(hidden)?

2024-03-18 15:17 UTC, mkaput commented on plugins/cairo-lang-macro/src/lib.rs
> +}
doc(hidden)?

2024-03-18 15:17 UTC, mkaput commented on plugins/cairo-lang-macro/src/lib.rs
> +}
doc(hidden)?

2024-03-18 15:26 UTC, mkaput requested changes

2024-03-18 15:26 UTC, mkaput commented on plugins/cairo-lang-macro/src/lib.rs
> +});
Do you really need to invest code into creating this hash map? Why not just find the item linearly in the source vector?

Anyway, I bet that for the amounts of items this collection will get, searching `vec` will be faster than making a hashmap and looking up there

2024-03-18 18:43 UTC, maciektr commented on plugins/cairo-lang-macro-attributes/src/lib.rs
>      let item_name = &item.sig.ident;
Yes, I thought about it and then forgot, sorry!

2024-03-19 09:31 UTC, mkaput requested changes

2024-03-19 09:31 UTC, mkaput commented on plugins/cairo-lang-macro/Cargo.toml
> +once_cell.workspace = true
unused now

2024-03-20 09:18 UTC, mkaput approved these changes

2024-03-20 10:57 UTC, merged