Replace result enum with single struct
software-mansion/scarb pull request #1249
Opened 2024-04-08 07:42 UTC by maciektr

2024-04-08 08:12 UTC, mkaput commented
Please rebase

2024-04-12 08:54 UTC, mkaput requested changes

2024-04-12 08:54 UTC, mkaput commented on scarb/tests/build_cairo_plugin.rs
> +            ProcMacroResult::new(TokenStream::new("".to_string()))
```suggestion
            ProcMacroResult::new(TokenStream::empty()))
```

wdyt?

2024-04-12 08:54 UTC, mkaput commented on scarb/tests/build_cairo_plugin.rs
Please add a test that attempts to remove inline macro

2024-04-12 21:07 UTC, maciektr commented
Closing pull request: commit has gone away

2024-04-12 21:07 UTC, closed without merging