Implement derive macros
software-mansion/scarb pull request #1258
Opened 2024-04-11 20:52 UTC by maciektr

2024-04-12 21:18 UTC, maciektr commented on scarb/src/compiler/plugin/proc_macro/host.rs
> +            return self.expand_attribute(input, token_stream, stable_ptr);
Note this takes a bit different approach to what we did before:
We remove the attribute, process it, and return expanded code. 
Following attributes will be processed in a subsequent macro calls.

2024-04-15 08:26 UTC, mkaput requested changes

2024-04-15 08:26 UTC, mkaput commented on scarb/src/compiler/plugin/proc_macro/host.rs
> +        if let Some(result) = self.expand_derives(db, item_ast.clone(), stream_metadata.clone()) {
would be good to have a test for following case:

```rust
#[macro1]
#[derive(Macro2)]
#[macro3]
struct Foo {}
```

2024-04-15 09:11 UTC, mkaput approved these changes

2024-04-15 10:03 UTC, merged