[scarb-doc] Scarb packages
software-mansion/scarb pull request #1289
Opened 2024-04-30 13:06 UTC by drknzz

2024-04-30 15:10 UTC, maciektr commented
Pls rebase

2024-05-06 10:54 UTC, maciektr requested changes

2024-05-06 10:54 UTC, maciektr commented on extensions/scarb-doc/src/main.rs
> +        .filter(|du| du.name != "core")
```suggestion
        .filter(|du| du.name != CORELIB_CRATE_NAME)
```

2024-05-06 10:54 UTC, maciektr commented on extensions/scarb-doc/src/main.rs
> +                    "Failed to find = {} package",
I would suggest using scarb style of error messages here as well, so please don't start with capital letters 
```suggestion
                    "failed to find `{}` package",
```

2024-05-06 10:54 UTC, maciektr commented on extensions/scarb-doc/src/main.rs
> +            .expect("Failed to find compilation unit for package");
```suggestion
            .expect("failed to find compilation unit for `{}` package", package_metadata.id.clone());
```

2024-05-07 09:37 UTC, maciektr approved these changes
lgtm!

2024-05-07 17:39 UTC, Arcticae reviewed
Can it select different crates from a workspace? 
I think this case should be tested

2024-05-08 17:25 UTC, drknzz commented on extensions/scarb-doc/src/main.rs
>  struct Args {
Already added 👍

2024-05-13 12:33 UTC, maciektr approved these changes

2024-05-13 12:33 UTC, maciektr commented on extensions/scarb-doc/tests/test.rs
> +    assert!(stdout.contains("/// Goodbye world"));
```suggestion
    assert!(stdout.contains("/// Goodbye world"));
    assert!(!stdout.contains("/// Hello world"));
```

2024-05-14 06:24 UTC, merged