PubGrub resolver initial impl, blocking, no-graph
software-mansion/scarb pull request #1453
Opened 2024-07-17 10:04 UTC by maciektr

2024-11-25 15:11 UTC, mkaput requested changes

2024-11-25 15:11 UTC, mkaput commented on scarb/src/resolver/algorithm/mod.rs
> +        .spawn(move || {
consider moving this to a separate named function to: reduce indentation, have something named in stack trace

2024-11-25 15:11 UTC, mkaput commented on scarb/src/resolver/algorithm/state.rs
> +            // and `SourceDispatch`, as well as the bounded request channel.
what do these two names refer to?

2024-11-26 10:58 UTC, wawel37 commented on scarb/src/resolver/algorithm/mod.rs
> +            anyhow::format_err!(
nit: import directly

2024-11-28 16:16 UTC, maciektr commented on Cargo.toml
> +pubgrub = { git = 'https://github.com/software-mansion-labs/pubgrub.git', branch = 'dev' }
`semver-pubgrub` depends on `pubgrub` as well 🫤

2024-11-29 08:41 UTC, mkaput commented on Cargo.toml
> +pubgrub = { git = 'https://github.com/software-mansion-labs/pubgrub.git', branch = 'dev' }
can't you change this dependency in our semver-pubgrub fork?

2025-01-07 11:43 UTC, mkaput commented on scarb/tests/http_registry.rs
> +        GET /index/3/b/bar.json
OK, I understand now the reason. The change you propose is just an optimization then, not a consequence of misbehaving, so I suggest just leaving an issue here and closing this thread :)

2025-01-08 12:32 UTC, mkaput approved these changes

2025-01-08 17:47 UTC, merged