Foldable sidebar: traits
software-mansion/scarb pull request #1468
Opened 2024-07-19 12:57 UTC by piotmag769

2024-07-19 13:02 UTC, piotmag769 reviewed
The general idea is to make a sidebar look like this, so the lists of items are foldable. To achieve this I need to generate additional files that are responsible for the foldable sections

<img width="279" alt="image" src="https://github.com/user-attachments/assets/8ccd71e3-ee6d-495c-ada4-112a0ce1d69a">

2024-07-19 13:02 UTC, piotmag769 commented on extensions/scarb-doc/src/docs_generation/markdown/traits.rs
> +}
Same idea as above, I will need the file names in `SUMMARY.md`, so I want to keep them hardcoded in one place

2024-07-22 12:01 UTC, piotmag769 commented on extensions/scarb-doc/src/docs_generation.rs
> +}
The purpose of this trait is to avoid hardcoding the names multiple times (just hardcode them here)

2024-07-22 12:01 UTC, piotmag769 commented on extensions/scarb-doc/src/docs_generation/markdown/traits.rs
> +}
The purpose of this trait is to avoid hardcoding the names multiple times (just hardcode them here)

2024-07-22 14:20 UTC, mkaput requested changes

2024-07-22 14:20 UTC, mkaput commented on extensions/scarb-doc/src/docs_generation.rs
> +}
1. wdyt?

```suggestion
trait ItemsName {
    const HEADER: &'static str;
}

macro_rules! impl_items_name {
    ($t:ty, $name:expr) => {
        impl ItemsName for $t {
            const HEADER: &'_ str = $name;
        }
    };
}
```

2. Why can't this be part of `DocItem` trait?

2024-07-22 15:02 UTC, mkaput approved these changes

2024-07-22 16:22 UTC, merged