Add derives to `cairo-lang-macro`
software-mansion/scarb pull request #1676
Opened 2024-10-24 14:05 UTC by Draggu

2024-10-24 15:28 UTC, maciektr commented
Can we hide it behind a feature (both dependency declaration and usages) to retain minimal set of deps for building macros on user side?

2024-10-25 11:44 UTC, mkaput requested changes
blocking because of https://github.com/software-mansion/scarb/pull/1676#issuecomment-2435609941

2024-11-04 14:19 UTC, mkaput approved these changes

2024-11-05 15:33 UTC, maciektr approved these changes

2024-11-06 11:39 UTC, piotmag769 approved these changes

2024-11-06 15:56 UTC, merged