Proc macro server API
software-mansion/scarb pull request #1678
Opened 2024-10-24 14:05 UTC by Draggu

**Stack**:
- #1677
- #1676

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-10-25 11:57 UTC, mkaput requested changes

2024-10-25 12:20 UTC, mkaput commented on utils/proc-macro-server-api/Cargo.toml
> +name = "proc-macro-server-api"
```suggestion
name = "scarb-proc-macro-server-types"
```

just like `lsp_types`, wdyt?

2024-10-25 12:34 UTC, mkaput requested changes

2024-10-25 12:34 UTC, mkaput commented on utils/proc-macro-server-api/src/lib.rs
> +}
it's impossible to determine whether response is successful or it carries an error

```suggestion
#[derive(Serialize, Deserialize)]
pub struct RpcResponse {
    pub id: RequestId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ResponseError>,
}
```

2024-11-04 12:27 UTC, merged

2024-11-04 14:23 UTC, Draggu commented
Some spr issues, please continue here #1715