Add request handling
software-mansion/scarb pull request #1682
Opened 2024-10-24 14:05 UTC by Draggu

**Stack**:
- #1681
- #1680
- #1679
- #1678
- #1677
- #1676

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-10-25 12:37 UTC, mkaput requested changes

2024-10-25 12:37 UTC, mkaput commented on scarb/src/ops/proc_macro_server/mod.rs
> +    for i in 0..4 {
use `std::thread:available_parallelism`. do not hardcode threading amounts

2024-10-25 12:37 UTC, mkaput commented on scarb/src/ops/proc_macro_server/json_rpc.rs
> +pub struct ErrResponse {
this should probably reside in proc-macros-server-api crate. I made a related comment about this in that PR: https://github.com/software-mansion/scarb/pull/1678#discussion_r1816600767

2024-10-25 12:37 UTC, mkaput commented on scarb/src/ops/proc_macro_server/mod.rs
please start adding tests for this system starting with this PR

2024-10-25 12:38 UTC, mkaput requested changes

2024-10-25 12:38 UTC, mkaput commented on scarb/src/ops/proc_macro_server/mod.rs
> +                    let response = match request.method.as_str() {
the indentation is going crazy here, please:
1. extract worker body to a separate function
2. extract request method routing to another one

2024-11-05 15:30 UTC, Draggu commented on scarb/src/ops/proc_macro_server/mod.rs
#1718 Started with next PR (new one) to not bloat diff here

2024-11-06 09:13 UTC, mkaput approved these changes

2024-11-06 13:36 UTC, piotmag769 approved these changes

2024-11-07 16:25 UTC, merged