Add `ExpandInline` handler
software-mansion/scarb pull request #1686
Opened 2024-10-24 14:05 UTC by Draggu

**Stack**:
- #1686 ⬅
- #1685
- #1684
- #1683
- #1682
- #1681
- #1680
- #1679
- #1678
- #1677
- #1676

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-10-25 12:47 UTC, mkaput requested changes

2024-10-25 12:47 UTC, mkaput commented on scarb/src/ops/proc_macro_server/methods/expand_inline.rs
missing tests

2024-11-07 17:10 UTC, piotmag769 commented on scarb/tests/proc_macro_server.rs
> +    assert_eq!(response.token_stream, args);
Same request as for attr macros: can we do anything here to see if it works?

2024-11-08 09:40 UTC, mkaput requested changes
blocking due to Piotr's comment

2024-11-08 12:38 UTC, mkaput approved these changes

2024-11-08 15:15 UTC, piotmag769 approved these changes

2024-11-09 20:32 UTC, merged