Run cairo tests for workspace
software-mansion/scarb pull request #465
Opened 2023-07-09 22:25 UTC by maciektr

**Stack**:
- #464
- #463
- #447
- #446
- #445
- #444

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-07-13 08:38 UTC, mkaput requested changes

2023-07-13 08:38 UTC, mkaput commented on scarb/src/bin/scarb/commands/test.rs
> +            .map(|package| ops::execute_test_subcommand(&package, &args.args, config, &ws))
I wonder if we shouldn't print a message saying "running tests for package {package}..." wdyt?

2023-08-01 09:19 UTC, mkaput requested changes

2023-08-01 11:41 UTC, mkaput approved these changes

2023-08-01 11:59 UTC, maciektr commented
✓ Commit merged in pull request [#490](https://github.com/software-mansion/scarb/pull/490)

2023-08-01 11:59 UTC, closed without merging