Run scripts for multiple selected packages
software-mansion/scarb pull request #500
Opened 2023-07-21 10:41 UTC by maciektr

**Stack**:
- #490
- #489
- #465
- #446
- #447
- #445

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-08-01 10:54 UTC, mkaput requested changes

2023-08-01 10:54 UTC, mkaput commented on scarb/src/bin/scarb/commands/run.rs
> +            "Scripts available via `scarb run` for `{}` package:",
```suggestion
            "Scripts available via `scarb run` for package `{}`:",
```

2023-08-03 13:33 UTC, mkaput requested changes

2023-08-03 13:33 UTC, mkaput commented on scarb/src/bin/scarb/commands/run.rs
> +                scarb run -p {package_name}
If you have single-package workspace, I would rather skip printing this argument

2023-08-03 14:33 UTC, mkaput approved these changes

2023-08-03 14:59 UTC, maciektr commented
✓ Commit merged in pull request [#508](https://github.com/software-mansion/scarb/pull/508)

2023-08-03 14:59 UTC, closed without merging