Warn on members definition match without manifest
software-mansion/scarb pull request #502
Opened 2023-07-21 14:42 UTC by maciektr

**Stack**:
- #500
- #490
- #489
- #465
- #446
- #447
- #445

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-08-01 10:56 UTC, mkaput requested changes

2023-08-01 10:56 UTC, mkaput commented on scarb/src/ops/workspace.rs
Please add a test for that

2023-08-01 10:56 UTC, mkaput commented on scarb/src/ops/workspace.rs
> +                            but the manifest file does not exist"
maybe "which misses a manifest file"? (+/- grammar)

2023-08-03 14:59 UTC, maciektr commented
✓ Commit merged in pull request [#508](https://github.com/software-mansion/scarb/pull/508)

2023-08-03 14:59 UTC, closed without merging